#pragma once

#include <Genode/IO/Json.hpp>
#include <Genode/IO/IOException.hpp>
#include <Genode/IO/Resource.hpp>
#include <Genode/IO/BufferedInputStream.hpp>
#include <Genode/IO/ResourceLoader.hpp>
#include <Genode/IO/ResourceLoaderFactory.hpp>
#include <Genode/IO/ResourceContainer.hpp>
#include <Genode/IO/ResourceContext.hpp>
#include <Genode/IO/FileInfo.hpp>
#include <Genode/IO/FileSystemController.hpp>
#include <Genode/IO/FileSystem.hpp>
#include <Genode/IO/LocalFileSystem.hpp>
#include <Genode/IO/Archive.hpp>
#include <Genode/IO/ResourceManager.hpp>
#include <Genode/IO/FontManager.hpp>
#include <Genode/IO/Loaders/FontLoader.hpp>
#include <Genode/IO/Loaders/SoundBufferLoader.hpp>
#include <Genode/IO/Loaders/TextureLoader.hpp>
